x-base-service: &base-service
  image: foo:bar #thekevjames/nox
  volumes:
    - .:/code
  working_dir: /code
  environment:
      - PYTHONPATH=/code
services:
  nox:
    <<: *base-service

  nox-tests-all:
    <<: *base-service
    command: nox --session tests

  nox-tests-3.10:
    <<: *base-service
    command: nox --session tests-3.10

  nox-check-formatting:
    <<: *base-service
    command: nox --session check_formating
