x-base-service: &base-service
  image: thekevjames/nox
  volumes:
    - .:/app
  working_dir: /app

services:
  nox-tests-all:
    <<: *base-service
    command: nox

  nox-tests-3.10:
    <<: *base-service
    command: nox --session tests-3.10

  nox-check-formatting:
    <<: *base-service
    command: nox --session check_formating
