version: '3.8'
services:
  nox:
    image: thekevjames/nox
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app  # Set working directory to /app
    command: nox  # Run nox; adjust as needed for specific sessions or arguments
