site_name: "Pytoolbelt Documentation"

markdown_extensions:
  - markdown_include.include

plugins:
  - mkdocstrings:
      handlers:
        python:
          show_source: false
  - search:
      lang: en

theme:
  name: "material"
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Initialize Pytoolbelt: install_dirs.md
  - Toolbelt: toolbelt.md
  - CLI: commands.md
