name: Release To PyPI

on:
  push:
    branches:
      - use-nox-in-ci

jobs:
  run_tests:
    name: Run Tests and Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker-compose pull nox

      - name: Run Formatting Checks
        run: docker-compose run nox-check-formatting

      - name: Run Tests
        run: docker-compose run nox-tests-all


#  release:
#    runs-on: ubuntu-latest
#    needs: run_tests
#    concurrency: release
#    environment: release
#    permissions:
#      id-token: write
#      contents: write
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - name: Python Semantic Release
#      id: release
#      uses: python-semantic-release/python-semantic-release@v8.0.6
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#
#
#    - name: Publish package distributions to PyPI
#      uses: pypa/gh-action-pypi-publish@release/v1
#      if: steps.release.outputs.released == 'true'
